#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarin.RecyclerView.SwipeMenu.Test.Resource", IsApplication=true)]

namespace Xamarin.RecyclerView.SwipeMenu.Test
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int sml_auto_open_percent = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int sml_scroller_duration = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int sml_scroller_interpolator = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040005
			public const int MyButton = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int ad_container = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int smContentView = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int smMenuViewBottom = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int smMenuViewLeft = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int smMenuViewRight = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int smMenuViewTop = 2130968580;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SwipeMenu = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int SwipeMenu_sml_auto_open_percent = 1;
			
			// aapt resource value: 0
			public const int SwipeMenu_sml_scroller_duration = 0;
			
			// aapt resource value: 2
			public const int SwipeMenu_sml_scroller_interpolator = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
